apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    name: my-rc
    type: frontend
spec:
  template:
    metadata:
      name: my-pod
      labels:
        name: my-pod
        type: frontend
    spec:
      containers:
        - image: nginx
          name: nginx
  replicas: 3 
